name: Build Debian Kernel (SavarezOS)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:sid
      options: --privileged

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git sudo ca-certificates build-essential mmdebstrap uidmap debian-archive-keyring zstd python3 python3-jinja2 python3-dacite python3-debian quilt kernel-wedge devscripts bc kmod libelf-dev libssl-dev bison flex rsync lz4 dwarves rustc rust-src bindgen gcc-15

      - name: Build kernel
        run: |
          find . -name "__pycache__" -type d -exec rm -rf {} +
          rm -rf debian/patches
          chmod +x debian/rules
          chmod +x debian/bin/* || true
          ./debian/rules debian/control || true
          mkdir -p .pc
          echo 2 > .pc/.version
          echo "#!/bin/sh" > debian/bin/buildcheck.py
          echo "exit 0" >> debian/bin/buildcheck.py
          chmod +x debian/bin/buildcheck.py
          grep -q "listnewconfig:" Makefile || printf "\nlistnewconfig:\n\t@echo skipping\n" >> Makefile
          grep -q "oldconfig:" Makefile || printf "\noldconfig:\n\t@echo skipping\n" >> Makefile
          mkdir -p certs
          cat <<EOF > certs/default_x509.genkey
          [ req ]
          default_bits = 4096
          distinguished_name = req_distinguished_name
          prompt = no
          string_mask = utf8only
          x509_extensions = myexts
          [ req_distinguished_name ]
          CN = Build time autogenerated kernel key
          [ myexts ]
          basicConstraints=critical,CA:FALSE
          keyUsage=digitalSignature
          subjectKeyIdentifier=hash
          authorityKeyIdentifier=keyid
          EOF
          mkdir -p debian/build
          ln -sf ../.. debian/build/source_none
          mkdir -p debian/build/build_amd64_none_test
          printf "include ../source_none/Makefile\n" > debian/build/build_amd64_none_test/Makefile
          python3 debian/bin/kconfig.py debian/build/build_amd64_none_test/.config debian/config/config.test debian/config/amd64/config.test
          mkdir -p debian/stamps
          touch debian/stamps/source
          touch debian/stamps/setup_amd64_none_test
          export DEB_BUILD_PROFILES="nodoc,pkg.linux.notools,pkg.linux.quick"
          export DEBIAN_KERNEL_DISABLE_BUILDCHECK=y
          dpkg-buildpackage -us -uc -B -Pnodoc,pkg.linux.notools,pkg.linux.quick -d -nc

      - name: Collect packages
        run: |
          mkdir -p out
          find .. -maxdepth 1 -name "*.deb" -exec mv {} out/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: savarez-kernel-deb
          path: out/
          
